#!/bin/bash
# pmos: cross-compile QEMU (x86_64-softmmu, in-process shared library) for
# arm64-apple-ios, together with the minimal dependency set.
#
# Adapted from Husk's scripts/build_ios.sh (Leviidev/Husk, GPL-2.0-or-later),
# which itself follows UTM's scripts/build_dependencies.sh for the toolchain
# shape (-target triple, meson cross-file, needs_exe_wrapper).
#
# Differences from Husk:
#   - target is x86_64-softmmu (postmarketOS generic-x86_64) not aarch64.
#   - no virgl/opengl/ANGLE: pmOS Phosh renders with llvmpipe over the
#     virtio-gpu 2D framebuffer, so the software display bridge is enough.
#   - the pmos engine sources are integrated BEFORE the build (single pass),
#     instead of Husk's build-then-rebuild.
#
# Usage: ./scripts/build-engine.sh [stage ...]   (no args = all stages)
#        stages: libffi glib pixman libucontext libslirp qemu stage
set -uo pipefail

PMOS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENGINE="$PMOS_ROOT/build/engine"
SRC="$ENGINE/src"
PREFIX="$ENGINE/sysroot"
LOGS="$ENGINE/logs"
STAMPS="$ENGINE/stamps"
mkdir -p "$PREFIX" "$LOGS" "$STAMPS"

ARCH=arm64
SDK=iphoneos
SDKMINVER="${SDKMINVER:-16.0}"
NCPU="$(sysctl -n hw.ncpu 2>/dev/null || echo 4)"

if ! command -v xcrun >/dev/null 2>&1; then
    echo "[FAIL] build-engine.sh requires macOS with Xcode (xcrun is missing)" >&2
    exit 1
fi
if ! command -v meson >/dev/null 2>&1; then
    echo "[FAIL] meson >= 1.5 required: pip3 install 'meson>=1.5' 'ninja'" >&2
    exit 1
fi
if ! command -v bzip2 >/dev/null 2>&1; then
    echo "[FAIL] bzip2 required (to unpack the OVMF edk2 blobs)" >&2
    exit 1
fi

SDKROOT="$(xcrun --sdk $SDK --show-sdk-path)"
SDKVERSION="$(xcrun --sdk $SDK --show-sdk-version)"
CFLAGS_TARGET="-target $ARCH-apple-ios$SDKMINVER"

export CC="$(xcrun --sdk $SDK --find clang) $CFLAGS_TARGET"
export CXX="$(xcrun --sdk $SDK --find clang++) $CFLAGS_TARGET"
export OBJCC="$(xcrun --sdk $SDK --find clang)"
export AR="$(xcrun --sdk $SDK --find ar)"
export NM="$(xcrun --sdk $SDK --find nm)"
export RANLIB="$(xcrun --sdk $SDK --find ranlib)"
export STRIP="$(xcrun --sdk $SDK --find strip)"
export LD="$(xcrun --sdk $SDK --find ld)"

export CFLAGS="-arch $ARCH -isysroot $SDKROOT -I$PREFIX/include $CFLAGS_TARGET -O2"
export CXXFLAGS="$CFLAGS"
export CPPFLAGS="-arch $ARCH -isysroot $SDKROOT -I$PREFIX/include $CFLAGS_TARGET"
export OBJCFLAGS="$CFLAGS"
export LDFLAGS="-arch $ARCH -isysroot $SDKROOT -L$PREFIX/lib $CFLAGS_TARGET"

# Cross pkg-config: look ONLY in our sysroot so host Homebrew libraries can
# never leak into an iOS link.
export PKG_CONFIG="$(command -v pkg-config)"
export PKG_CONFIG_LIBDIR="$PREFIX/lib/pkgconfig:$PREFIX/share/pkgconfig"
unset PKG_CONFIG_PATH

banner() { printf '\n\033[0;32m=== %s ===\033[0m\n' "$*"; }
fail()   { printf '\033[0;31m[FAIL] %s (see %s)\033[0m\n' "$1" "$2"; exit 1; }

done_stage() { [ -f "$STAMPS/$1" ]; }
mark_stage() { touch "$STAMPS/$1"; }

meson_quote() { echo "'$(echo $* | sed "s/ /','/g")'"; }

gen_cross() {
    local cross="$1" system="$2"
    cat > "$cross" <<EOF
# Automatically generated by pmos build-engine.sh - do not edit
[properties]
needs_exe_wrapper = true
[built-in options]
c_args = [$(meson_quote $CFLAGS)]
cpp_args = [$(meson_quote $CXXFLAGS)]
objc_args = [$(meson_quote $OBJCFLAGS)]
objcpp_args = [$(meson_quote $OBJCFLAGS)]
c_link_args = [$(meson_quote $LDFLAGS)]
cpp_link_args = [$(meson_quote $LDFLAGS)]
objc_link_args = [$(meson_quote $LDFLAGS)]
objcpp_link_args = [$(meson_quote $LDFLAGS)]
[binaries]
c = [$(meson_quote $CC)]
cpp = [$(meson_quote $CXX)]
objc = [$(meson_quote $OBJCC)]
objcpp = [$(meson_quote $OBJCC)]
ar = ['$AR']
nm = ['$NM']
ranlib = ['$RANLIB']
strip = ['$STRIP', '-x']
pkg-config = ['$PKG_CONFIG']
pkgconfig = ['$PKG_CONFIG']
python = ['$(command -v python3)']
[host_machine]
system = '$system'
EOF
    if [ "$system" = "darwin" ]; then
        echo "kernel = 'xnu'" >> "$cross"
        echo "subsystem = 'ios'" >> "$cross"
    fi
    cat >> "$cross" <<EOF
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'
EOF
}

CROSS_IOS="$ENGINE/cross-ios.meson"
CROSS_DARWIN="$ENGINE/cross-darwin.meson"
gen_cross "$CROSS_IOS" ios
gen_cross "$CROSS_DARWIN" darwin

# ---------------------------------------------------------------- autotools
build_autotools() {
    local name="$1"; shift
    local dir="$SRC/$name"
    local log="$LOGS/$name.log"
    done_stage "$name" && { echo "[skip] $name"; return 0; }
    banner "building $name (autotools)"
    ( cd "$dir" \
      && ./configure --host=aarch64-apple-darwin --prefix="$PREFIX" \
                     --enable-static --disable-shared "$@" \
      && make -j"$NCPU" \
      && make install ) > "$log" 2>&1 || fail "$name" "$log"
    mark_stage "$name"
}

# ---------------------------------------------------------------- meson
build_meson() {
    local name="$1" cross="$2"; shift 2
    local dir="$SRC/$name"
    local log="$LOGS/$name.log"
    done_stage "$name" && { echo "[skip] $name"; return 0; }
    banner "building $name (meson)"
    rm -rf "$dir/_pmos_build"
    ( cd "$dir" \
      && meson setup _pmos_build --cross-file "$cross" --prefix="$PREFIX" \
                --buildtype=release --default-library=static "$@" \
      && meson compile -C _pmos_build -j "$NCPU" \
      && meson install -C _pmos_build ) > "$log" 2>&1 || fail "$name" "$log"
    mark_stage "$name"
}

apply_patch() {
    local dir="$1"
    local patch="$2"
    local stamp="$SRC/$dir/.pmos-patched"
    [ -f "$stamp" ] && return 0
    [ -f "$PMOS_ROOT/patches/$patch" ] || return 0
    echo "[patch] $dir <- $patch"
    ( cd "$SRC/$dir" && patch -p1 -N -r - < "$PMOS_ROOT/patches/$patch" ) >/dev/null 2>&1
    touch "$stamp"
}

# ---------------------------------------------------------------- stages
stage_libffi()      { build_autotools libffi-3.5.0; }
stage_glib()        { build_meson glib-2.83.0 "$CROSS_IOS" \
                        -Dtests=false -Dnls=disabled -Dintrospection=disabled \
                        -Dselinux=disabled -Dlibmount=disabled -Ddtrace=disabled \
                        -Dman-pages=disabled -Dglib_debug=disabled -Dxattr=false; }
stage_pixman()      { apply_patch pixman-0.38.0 pixman-0.38.0.patch
                      build_autotools pixman-0.38.0 --disable-gtk --disable-libpng --disable-arm-iwmmxt; }
stage_libucontext() { build_meson libucontext "$CROSS_IOS" -Dfreestanding=true; }
stage_libslirp()    { apply_patch libslirp-v4.9.1 libslirp-v4.9.1.patch
                      build_meson libslirp-v4.9.1 "$CROSS_DARWIN"; }

stage_qemu() {
    local dir="$SRC/qemu-10.0.12-utm"
    local log="$LOGS/qemu.log"
    done_stage qemu && { echo "[skip] qemu"; return 0; }
    apply_patch qemu-10.0.12-utm qemu-10.0.12-utm.patch

    if [ ! -d "$ENGINE/.integrated" ]; then
        banner "integrating pmos engine sources into the QEMU tree"
        "$PMOS_ROOT/scripts/integrate-engine.sh" || fail integrate "$log"
        touch "$ENGINE/.integrated"
    fi

    banner "building qemu (this is the long one)"
    rm -rf "$dir/_pmos_build"; mkdir -p "$dir/_pmos_build"
    ( cd "$dir/_pmos_build" \
      && ../configure \
            --prefix="$PREFIX" \
            --cross-prefix="" \
            --target-list=x86_64-softmmu \
            --enable-shared-lib \
            --with-coroutine=libucontext \
            --enable-slirp \
            --disable-cocoa --disable-sdl --disable-gtk --disable-coreaudio \
            --disable-vnc --disable-spice \
            --disable-opengl --disable-virglrenderer \
            --disable-curses --disable-curl --disable-libusb --disable-usb-redir \
            --disable-tpm --disable-docs --disable-guest-agent --disable-tools \
            --disable-hvf --disable-vde --disable-brlapi --disable-libssh \
            --disable-bzip2 --disable-snappy --disable-lzo --disable-gnutls \
            --disable-png --disable-vte --disable-zstd \
            --disable-nettle --disable-gcrypt --disable-auth-pam \
            --disable-install-blobs --disable-sparse --disable-debug-info \
            --extra-cflags="$CFLAGS" --extra-ldflags="$LDFLAGS" \
      && make -j"$NCPU" ) > "$log" 2>&1 || fail qemu "$log"
    stage_engine
    mark_stage qemu
}

stage_engine() {
    local src="$SRC/qemu-10.0.12-utm/_pmos_build/libqemu-x86_64-softmmu.dylib"
    [ -f "$src" ] || return 0
    mkdir -p "$ENGINE/lib"
    cp "$src" "$ENGINE/lib/"
    # OVMF firmware blobs for the bundle: decompress the pinned edk2 pieces the
    # ROM ships as pc-bios/. (edk2 blobs are 0BSD/BSD-2-Clause from tianocore.)
    if ! command -v bzip2 >/dev/null 2>&1; then
        echo "[warn] bzip2 unavailable; skipping OVMF decompression" >&2
        return 0
    fi
    local pb="$SRC/qemu-10.0.12-utm/pc-bios"
    mkdir -p "$ENGINE/lib/pc-bios" "$ENGINE/lib/firmware"
    # The whole pc-bios directory minus the compressed edk2 blobs: whatever
    # QEMU looks up at runtime (-L <bundle>/pc-bios) is present.
    ( cd "$pb" && find . -maxdepth 1 -type f ! -name '*.bz2' -exec cp {} "$ENGINE/lib/pc-bios/" \; )
    bzip2 -dkf "$pb/edk2-x86_64-code.fd.bz2" -c > "$ENGINE/lib/pc-bios/edk2-x86_64-code.fd"
    bzip2 -dkf "$pb/edk2-i386-vars.fd.bz2"  -c > "$ENGINE/lib/pc-bios/edk2-i386-vars.fd"
    # Explicit, self-describing copies for the manifest's firmware/ entries.
    cp "$ENGINE/lib/pc-bios/edk2-x86_64-code.fd" "$ENGINE/lib/firmware/OVMF_CODE.fd"
    cp "$ENGINE/lib/pc-bios/edk2-i386-vars.fd"   "$ENGINE/lib/firmware/OVMF_VARS.fd"
    echo "[stage] $(cd "$ENGINE/lib" && pwd)"

    # Report what would break next time the ROM needs it. The dylib must
    # contain the exported host symbols.
    local exported
    exported="$(nm -gU "$ENGINE/lib/libqemu-x86_64-softmmu.dylib" | grep -c 'T _nxp_')"
    echo "[check] $exported exported T nxp_ backend symbols"
}

STAGES=("$@")
[ ${#STAGES[@]} -eq 0 ] && STAGES=(libffi glib pixman libucontext libslirp qemu)

echo "pmos engine build: PREFIX=$PREFIX"
echo "                   SDK=$SDKROOT ($SDKVERSION), min=$SDKMINVER, ncpu=$NCPU"
for s in "${STAGES[@]}"; do "stage_$s"; done
banner "build complete"
ls -la "$ENGINE/lib" 2>/dev/null | head -20